### ISSUE TITLE
Token "admin" is invalid - Postgres ERROR 22P02

### ISSUE THREAD

**Issue by gpproton** [jason-dark/supabase-drizzle#2]
Hi, i've been experiencing errors with running the generated migrations for as simple supabase test project mostly similar to the example here https://github.com/jason-dark/supabase-drizzle/tree/master/examples/basic-example.
I'd appreciate any recommendations on fixing the error and thanks for this cool package it's pontentialy going to make things easier for alot of supabase users.

Thanks.

### Versions

drizzle-orm: ^0.36.1
drizzle-kit: ^0.28.0
postgres: ^3.4.5
supabase-drizzle: ^1.1.2

```shell
npx drizzle-kit generate --config ./supabase/drizzle.config.ts && \
npx supabase-drizzle generate --config  ./supabase/drizzle.config.ts && \
npx drizzle-kit migrate --config  ./supabase/drizzle.config.ts
```

```shell
PostgresError: invalid input syntax for type json
    at ErrorResponse (file:///home/leanny/sandbox/ying-supabase/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/leanny/sandbox/ying-supabase/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/leanny/sandbox/ying-supabase/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '22P02',
  detail: 'Token "admin" is invalid.',
  where: 'JSON data, line 1: admin',
  file: 'jsonfuncs.c',
  line: '627',
  routine: 'json_ereport_error'
}
```

```typescript
// schema.ts
import { pgSchema, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

const authSchema = pgSchema('auth');

export const users = authSchema.table('users', {
    id: uuid('id').primaryKey(),
});

export const userRoles = pgTable('user_roles', {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id')
        .references(() => users.id)
        .unique()
        .notNull(),
    userRole: text('user_role').notNull(),
});

export const profiles = pgTable('profiles', {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id')
        .references(() => users.id)
        .unique(),
    firstName: text('first_name'),
    lastName: text('last_name'),
    email: text('email').notNull().unique(),
});

export const articles = pgTable('articles', {
    id: uuid('id').primaryKey(),
    title: text('title').notNull(),
    content: text('content').notNull(),
    userId: uuid('user_id').references(() => users.id),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at')
        .notNull()
        .$onUpdate(() => new Date()),
});

export type InsertUser = typeof users.$inferInsert;
export type SelectUser = typeof users.$inferSelect;

export type InsertArticle = typeof users.$inferInsert;
export type SelectArticle = typeof users.$inferSelect;
```

```typescript
// policies.config.ts
import { rlsPolicyBuilder } from 'supabase-drizzle';
import * as schema from './supabase/schema';

// @ts-ignore
const { tables, own, rls, authenticated, everyone, hasRole } = rlsPolicyBuilder(schema, {
    userRolesTable: schema.userRoles,
    userRoles: {
        owner: {},
        admin: {},
        member: {},
    },
});

const openPermissions = {
    select: everyone(),
    insert: everyone(),
    update: everyone(),
    delete: [own(), hasRole(['admin', 'owner'])],
    // delete: authenticated(),
};

const authPermissions = {
    select: authenticated(),
    insert: authenticated(),
    update: authenticated(),
    delete: authenticated(),
};

export const users = rls(tables.users, authPermissions);
export const userRoles = rls(tables.userRoles, authPermissions);
export const profiles = rls(tables.profiles, openPermissions);
export const articles = rls(tables.articles, {
    insert: authenticated(),
    update: own(),
    select: everyone(),
    delete: [own(), hasRole(['admin', 'owner'])],
    // delete: authenticated(),
});
```

**Comment by gpproton** [comment]
There were major improvements related to role management in the version of drizzle orm refrenced here https://github.com/drizzle-team/drizzle-orm/releases/tag/0.36.0

**Comment by jason-dark** [comment]
Hi given that `drizzle-orm` now supports RLS there is little to gain from using `supabase-drizzle`. I made this package to plug a gap that has now mostly been filled. I will update the readme for this project and direct people to the [Drizzle ORM RLS with Supabase docs](https://orm.drizzle.team/docs/rls#using-with-supabase).

**Comment by gpproton** [comment]
Thanks I'll explore how to use it
